version: '3'
services:
  nosql-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - ./db/:/data/db

  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/products/node_modules

  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    container_name: shopping
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/shopping/node_modules

  customers:
    build:
      dockerfile: Dockerfile
      context: ./customers
    container_name: customers
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/customers/node_modules
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - products
      - customers
      - shopping
    ports:
      - "80:80"
